### ISSUE TITLE
Please add support for recent versions of zlib and MonadRandom

### ISSUE THREAD

**Issue by peti** [mhwombat/creatur#1]
Hi, I would like to build your package with the Nix package manager, but unfortunately the build fails because Nix ships versions of `zlib` and `MonadRandom` that are too new for the versions constraints your Cabal file specifies: we have `zlib-0.6.1.1` and `MonadRandom-0.4` already. Would it be possible to get a new release of `creatur` on Hackage that supports the latest versions of these libraries?

**Comment by timthelion** [comment]
Doesn't nix have a way to install multiple packages side by side without conflict? I thought doing that was the whole point of nix.

**Comment by peti** [comment]
Sure, it is possible. But the fact that it's possible to maintain _x_ versions of the same library doesn't mean that it's a desirable thing to do.

**Comment by mhwombat** [comment]
Done. I did this on a non-NixOS machine. Still haven't managed to get Créatúr to build under NixOS.
